name: Build and Deploy

on:
  push:
    branches:
      - main  # Adjust to match your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.*  # Adjust to your Node.js version

      - name: Install project dependencies
        run: |
          npm install
          composer install --no-dev

      - name: Build the JavaScript project
        run: npm run build  # Adjust to your build command
      
      - name: Deploy the build
        run: |
          cd udosenakane.github.io
          rm -rf *
          mv dist/* ./